### ISSUE TITLE
up2p issue

### ISSUE THREAD

**Issue by pmoulon** [PoseLib/PoseLib#7]
Hello, thank you for sharing this great resource. Nice to see so many solvers at the same place.

I was playing with up2p and I have some issue on synthetic data:

GT Pose matrix [R|t]:
```
 -0.188982         0         0         0
        0  0.188982         0         0
        0         0 -0.188982  0.944911
```
Here the two solutions found by the solver [R|t]:
```
  0.0251174   0.187253          0 -0.0154913
 -0.187253  0.0251174          0 -0.0177079
         0          0    0.18893   -0.94465

 -0.0326047  -0.210253          0  0.0146222
  0.210253 -0.0326047          0  0.0180327
         0          0   0.212766   0.929329
```

Any idea what could be wrong. It seems that very close values are found but there is a flip in the rotation matrix.

In my code I assume I have gravity is Y aligned.
I saw this comment in the readme 

> Change upright solvers so that gravity is y-aligned (instead of z-aligned)

Do you think this is the issue I encounter, if yes, how can I help?

**Comment by vlarsson** [comment]
Yes, I think this is probably related to the y-axis vs z-axis gravity. The code assumes that you the rotations are of the form
R = [a -b 0; b a 0; 0 0 1]
so pure rotation around z-axis, which is not satisfied by your GT pose matrix.

I was working on a project where gravity was z-aligned when I was implementing the solvers. However, I think having gravity y-aligned, i.e. rotations like
R = [a 0 -b; 0 1 0; b 0 a]
is more natural and I want to switch all the solvers over to this. One quick fix would be to rotate the input, and then rotate the output poses back. In the long run I ideally want to update the solvers to directly solve for y-axis gravity. I have the scripts that I used to derive the coefficients for the solvers, so assuming I can find the code again, it should not be too much work.

For this solver there is also the issue #4, which is probably also a problem for the particular rotation you have :)

**Comment by pmoulon** [comment]
Thank you for your feedback.

I made a quick test and I found that the following solver are not robust to Y-axis gravity (using Benchmark) `up2p, ugp2p, ugp3ps, up1p2pl, up4pl`. All the others seem to react ok.

I'm gonna try to either fix the rotation matrix by hand for `up2p` or apply the rotation trick you spoke about.

**Comment by pablospe** [comment]
I think that instead of creating the solvers again, one could create a function that rotates the input to the desired form (the quick fix mentioned by Viktor). By creating a rotation matrix between two vectors, this would to be done only once anyways (before Ransac, for example), so it is not much overhead.

For instance, rotation between the `know_axis` (gravity) against the assumed gravity to the solver:
`Rg = rotation_between_vectors( know_axis, [0;0;1] )`

It is better explained [here ](http://openaccess.thecvf.com/content_cvpr_2018/Supplemental/2462-supp.pdf
)(section 1.1):

**Comment by pablospe** [comment]
Actually I have this function in Matlab (it is more generic than the one derived in the .pdf):

```
%
% Find rotation matrix R such as
%     b = R*a
% where 'a' and 'b' are unit vectors.
%
% If 'v = a x b' then
%   sin(th) = norm(v)
%   cos(th) = dotproduct(a,b)
%
function R = rotation_between_vectors(a, b)
    % force unit vector
    if abs(norm(a) - 1) > eps || abs(norm(b) - 1) > eps
        warning("rotation_between_vectors(a, b): 'a' and 'b' most be unit vectors.")
        a = a / norm(a);
        b = b / norm(b);
    end

    % orthogal vector
    v = skew3(a)*b;
    w = v/norm(v);

    % compute sin and cos (instead of getting th angle directly)
    cos_th = a'*b;
    sin_th = norm(v);

    % Rodrigues' formula
    R = eye(3) + (sin_th*skew3(w)) + (1-cos_th)*skew3(w)^2;
end

function S = skew3(v)
    S = [   0   -v(3)  v(2)
           v(3)   0   -v(1)
          -v(2)  v(1)   0 ];
end
```

**Comment by vlarsson** [comment]
There is also
 Eigen::Quaterniond::FromTwoVectors
so I don't think we need to implement this ourselves.

In practice I agree that it does not matter (users can simply rotate the 3D points as you said), however, I think y-axis as gravity is more natural.

I think the motivation for implementing the quick fix now (before rewriting the solvers) would be that the interface would stay the same once we actually fix it.

**Comment by pmoulon** [comment]
I tried quickly something like this:

-> Assuming we have now y-axis oriented data in the benchmark.
```
// Compute rotation from A to B (changing gravity from Y to Z)
const Eigen::Matrix3d gravity_rot =
    Eigen::Quaterniond::FromTwoVectors(
        Eigen::Vector3d::UnitY(),
        Eigen::Vector3d::UnitZ()).toRotationMatrix();
// Rotate world points
for (auto & pt : X)
{
  pt = gravity_rot * pt;
}
```

It would fix gravity for the estimation, but then we need to fix it back on the pose:
```
// Rotate back pose from Z to Y-axis gravity
pose.R = gravity_rot.transpose() * pose.R;
pose.t = gravity_rot.transpose() * pose.t;
```

But it seems not working yet... Can you help me figure it out what would be wrong...?

**Comment by vlarsson** [comment]
To take 
`R = [a -b 0; b a 0; 0 0 1]`
to 
`R = [a 0 -b; 0 1 0; b 0 a]`

you need to multiply from both sides, i.e. 
```
pose.R = gravity_rot.transpose() * pose.R *  gravity_rot;
pose.R = gravity_rot.transpose() * pose.t;
```
which means you need to change coordinate systems in both the image points and 3D points. Both should be rotated by gravity_rot, i.e.
```
for (auto & pt : x)
{
  pt = gravity_rot * pt;
}
for (auto & pt : X)
{
  pt = gravity_rot * pt;
}
```
I think this should be correct at least :)

**Comment by pmoulon** [comment]
Basically, we have two ways to handle this:
1. a GravityFixSolver function decorator. We could decorate the ZAxis to be YAxis by using the transform trick at solving time and fix the poses, but it will add a bit of overhead.
2. Or else, we preprocess all the points, then we need to post-process back the pose and I don't see how to do that without changing a lot the design

```

struct SolverUP2P {
  static inline int solve(const ProblemInstance &instance, pose_lib::CameraPoseVector *solutions) {
   return GravityDecoratorZY(instance.x_point_, instance.X_point_, solutions, up2p)
  }
  typedef CalibPoseValidator validator;
  static std::string name() { return "up2p"; }
};
```

```
int GravityDecorator(x, X, solutions, functor)
{
const Eigen::Matrix3d gravity_rot =
        Eigen::Quaterniond::FromTwoVectors(
          Eigen::Vector3d::UnitZ(),
          -Eigen::Vector3d::UnitY()).toRotationMatrix();
// Fix gravity on points (X,x)
for (auto & pt : X)
{
  pt = gravity_rot * pt;
}
for (auto & pt : x)
{
  pt = gravity_rot * pt;
}

// Call Solver
int sol = functor(x,X,solutions)

// Fix poses
for (auto pose : poses)
{
  pose.R = gravity_rot.transpose() * pose.R * gravity_rot;
  pose.t = gravity_rot.transpose() * pose.t;
}
return sol;
}
```

What do you think?
 - do you want me to make a proposal with the Decorator?

**Comment by vlarsson** [comment]
Hmm, I am not sure. I think it's better to directly update the solvers to use y-gravity. 

Maybe we can add an interface that takes general gravity vector, so we would have

int up2p(const std::vector<Eigen::Vector3d> &x, const std::vector<Eigen::Vector3d> &X, CameraPoseVector *output);
int up2p(const std::vector<Eigen::Vector3d> &x, const std::vector<Eigen::Vector3d> &X, const Eigen::Vector3d &gravity, CameraPoseVector *output);

where the second version is essentially what you have above, but for general gravity (instead of z) and then calls the original solver. Then the user can decide to pre-rotate the coordinate system if they want best performance, or if they don't care, they get cleaner code.

Maybe there is a nice design with decorators as well, instead of duplicating this code on all solvers. I could see problems since the different solvers have different inputs (points/lines and so on), so you might end up with the code duplication anyways, just in another file :)

We might want to restructure a bit and create a utils folder (or something like this), and then maybe move univariate.cc to this. I am doing some benchmarking with faster QEP solvers (for up4pl) which would fit there as well. These decorators could fit there as well then.

**Comment by pablospe** [comment]
> int up2p(const std::vectorEigen::Vector3d &x, const std::vectorEigen::Vector3d &X, const Eigen::Vector3d &gravity, CameraPoseVector *output);

I think this is a good option. But in a ransac loop, pre-rotating the coordinate could be done only one time for all data instead of calling the second `up2p` -- fixing the gravity data -- every time (well, depending of the problem), so also exposing little tools that do this would be desirable, and this generic code could even be used also inside the new `u<solver>` functions. Basically, exposing the code inside the GravityDecorator, in two functions: 1. fixing points, 2. fixing poses.

**Comment by vlarsson** [comment]
In 2c65769 I updated the upright solvers such that they solve for y-aligned gravity. I will keep this issue open since I have not added the fix  for the degenerate case yet.

**Comment by pmoulon** [comment]
Thx you @vlarsson 
Can you elaborate for the degenerate case?

**Comment by vlarsson** [comment]
For the upright solvers we implement the rotations using Weierstrass substitution (I think all of them use it) such that

R = [a 0 b; 0 1 0; -b 0 a]

a = (1 - q*q) / (1 + q*q)
b = 2 * q / (1 + q*q)

To represent the rotation a = -1, b = 0, we must let q -> infinity. So the solvers should degenerate if the ground truth rotation is

R = [-1 0 0; 0 1 0; 0 0 -1]

I would also guess rotations that are close to this will have poor numerical stability (since you need very large values for q). 

Best,
Viktor

**Comment by pmoulon** [comment]
Thank you for the explanation.
Do you think adding a test on q in order to return no model in case of degeneracy detected would be useful?
It would involve a threshold, but at least would make the degenerate case obvious for the developer to see.

**Comment by vlarsson** [comment]
It is only a degeneracy in the solver and not inherent to the problem itself, so it is still solvable. I think there are three reasonable options to fix this;
1. As you suggested, add some check to figure out if it is degenerate. The main problem with this is to ensure that this check becomes robust (probably involving some extra hyperparameters which is not very nice). If the instance is (close to) degenerate, we can rotate the problem an solve again.
2. Randomly rotate each time before solving. This is what is currently done for the Cayley based solvers (gp4ps/gp3p/...).
3. Solve problem twice, rotated 180 degrees. This clearly has the problem with double the runtime cost :) but should be guaranteed to work. I guess there will be some code to remove duplicate solutions which is not very nice.

I think any of these solutions are fine, but I guess the random rotation is the easiest one to implement.

**Comment by alexs7** [comment]
@pmoulon Hello, I wanted to ask, once you have the 2D-3D matches you have to then rotate the 2D coordinates and 3D coordinates before passing to the up2p function, by the IMY values that give Rx and Rz ?
